# Generated by Django 3.2.7 on 2022-03-25 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_number', models.CharField(max_length=25, verbose_name='Customer Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('building_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Building Type')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('total_price', models.FloatField(verbose_name='Total Price')),
                ('total_quantity', models.IntegerField(verbose_name='Total Quantity')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relates_order_user', to='accounts.user')),
            ],
        ),
    ]
